- alias: Set target humidity Zone 1
  description: ''
  trigger:
  - entity_id: input_number.target_humidity_zone1
    platform: state
  condition: []
  action:
  - data_template:
      entity_id: humidity.hygrostat_zone_1
      humidity: "{{ trigger.to_state.state }}"
    service: humidity.set_humidity
- alias: Set target humidity Zone 2
  description: ''
  trigger:
  - entity_id: input_number.target_humidity_zone2
    platform: state
  condition: []
  action:
  - data_template:
      entity_id: humidity.hygrostat_zone_2
      humidity: "{{ trigger.to_state.state }}"
    service: humidity.set_humidity
- alias: Set target humidity Zone 3
  description: ''
  trigger:
  - entity_id: input_number.target_humidity_zone3
    platform: state
  condition: []
  action:
  - data_template:
      entity_id: humidity.hygrostat_zone_3
      humidity: "{{ trigger.to_state.state }}"
    service: humidity.set_humidity
