- alias: humidifier_zone1
  trigger:
    - platform: state
      entity_id: sensor.zone1_humidity, input_number.target_humidity_zone1
    - platform: homeassistant
      event: start
  action:
    service_template: >
      {% if states.sensor.zone1_humidity.state | float < states.input_number.target_humidity_zone1.state | float %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
    data:
      entity_id: switch.p0_0
- alias: humidifier_zone2
  trigger:
    - platform: state
      entity_id: sensor.zone2_humidity, input_number.target_humidity_zone2
    - platform: homeassistant
      event: start
  action:
    service_template: >
      {% if states.sensor.zone2_humidity.state | float < states.input_number.target_humidity_zone2.state | float %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
    data:
      entity_id: switch.p0_1
- alias: humidifier_zone3
  trigger:
    - platform: state
      entity_id: sensor.zone3_humidity, input_number.target_humidity_zone3
    - platform: homeassistant
      event: start
  action:
    service_template: >
      {% if states.sensor.zone3_humidity.state | float < states.input_number.target_humidity_zone3.state | float %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
    data:
      entity_id: switch.p0_2

