- alias: Set target humidity Zone 1
  trigger:
  - entity_id: input_number.target_humidity_zone1
    platform: state
  condition: []
  action:
  - data_template:
      entity_id: humidity.hygrostat_zone_1
      humidity: "{{ trigger.to_state.state }}"
    service: humidity.set_humidity
- alias: Set target humidity Zone 2
  trigger:
  - entity_id: input_number.target_humidity_zone2
    platform: state
  condition: []
  action:
  - data_template:
      entity_id: humidity.hygrostat_zone_2
      humidity: "{{ trigger.to_state.state }}"
    service: humidity.set_humidity
- alias: Set target humidity Zone 3
  trigger:
  - entity_id: input_number.target_humidity_zone3
    platform: state
  condition: []
  action:
  - data_template:
      entity_id: humidity.hygrostat_zone_3
      humidity: "{{ trigger.to_state.state }}"
    service: humidity.set_humidity
- alias: Pump control
  trigger:
  - entity_id: switch.zone1, switch.zone2, switch.zone3
    platform: state
  condition: []
  action:
  - service_template: >
      {% if is_state('switch.zone1', 'on') or is_state('switch.zone2', 'on') or is_state('switch.zone3', 'on') %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
    data:
      entity_id: switch.pump
- alias: Toggle switch Zone 1
  trigger:
  - platform: state
    entity_id: input_boolean.humidify_zone1
  condition: []
  action:
  - service_template: >
      {% if is_state('input_boolean.humidify_zone1', 'on') %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
    data:
      entity_id: switch.zone1
- alias: Toggle switch Zone 2
  trigger:
  - platform: state
    entity_id: input_boolean.humidify_zone2
  condition: []
  action:
  - service_template: >
      {% if is_state('input_boolean.humidify_zone2', 'on') %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
    data:
      entity_id: switch.zone2
- alias: Toggle switch Zone 3
  trigger:
  - platform: state
    entity_id: input_boolean.humidify_zone3
  condition: []
  action:
  - service_template: >
      {% if is_state('input_boolean.humidify_zone3', 'on') %}
      switch.turn_on
      {% else %}
      switch.turn_off
      {% endif %}
    data:
      entity_id: switch.zone3
- alias: Limit Work Time Zone 1
  trigger:
  - platform: state
    entity_id: switch.zone1
    to: "on"
    for:
      seconds: "{{ states('input_number.working_time')|int }}"
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.zone1
- alias: Limit Work Time Zone 2
  trigger:
  - platform: state
    entity_id: switch.zone2
    to: "on"
    for:
      seconds: "{{ states('input_number.working_time')|int }}"
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.zone2
- alias: Limit Work Time Zone 3
  trigger:
  - platform: state
    entity_id: switch.zone3
    to: "on"
    for:
      seconds: "{{ states('input_number.working_time')|int }}"
  condition: []
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.zone3
- alias: Limit Idle Time Zone 1
  trigger:
  - platform: state
    entity_id: switch.zone1
    to: "off"
    for:
      seconds: "{{ states('input_number.idle_time')|int }}"
  condition:
  - condition: state
    entity_id: input_boolean.humidify_zone1
    state: "on"
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.zone1
- alias: Limit Idle Time Zone 2
  trigger:
  - platform: state
    entity_id: switch.zone2
    to: "off"
    for:
      seconds: "{{ states('input_number.idle_time')|int }}"
  condition:
  - condition: state
    entity_id: input_boolean.humidify_zone2
    state: "on"
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.zone2
- alias: Limit Idle Time Zone 3
  trigger:
  - platform: state
    entity_id: switch.zone3
    to: "off"
    for:
      seconds: "{{ states('input_number.idle_time')|int }}"
  condition:
  - condition: state
    entity_id: input_boolean.humidify_zone3
    state: "on"
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.zone3
