
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
homeassistant:
  customize: !include customize.yaml

switch:
  - platform: pcal9535a
    i2c_address: 0x20
    pins:
      0: Zone1
      1: Zone2
      2: Zone3
      3: Pump

sensor:
  - platform: season
    type: astronomical

input_number:
  target_humidity_zone1:
    name: Target humidity for zone 1
    min: 0
    max: 100
    unit_of_measurement: '%'
    icon: mdi:cogs
  target_humidity_zone2:
    name: Target humidity for zone 2
    min: 0
    max: 100
    unit_of_measurement: '%'
    icon: mdi:cogs
  target_humidity_zone3:
    name: Target humidity for zone 3
    min: 0
    max: 100
    unit_of_measurement: '%'
    icon: mdi:cogs
  idle_time:
    name: Idle time
    min: 0
    max: 600
    mode: box
    unit_of_measurement: 'sec'
    icon: mdi:clock
  working_time:
    name: Working time
    min: 0
    max: 600
    mode: box
    unit_of_measurement: 'sec'
    icon: mdi:clock-outline

input_boolean:
  humidify_zone1:
    name: Humidifying Zone 1
    initial: false
    icon: mdi:water
  humidify_zone2:
    name: Humidifying Zone 2
    initial: false
    icon: mdi:water
  humidify_zone3:
    name: Humidifying Zone 3
    initial: false
    icon: mdi:water

humidity:
  - platform: generic_hygrostat
    name: Hygrostat Zone 1
    humidifier: input_boolean.humidify_zone1
    target_sensor: sensor.zone1_humidity
    min_humidity: 0
    max_humidity: 100
    dry_mode: false
    target_humidity: 50
    dry_tolerance: 3
    wet_tolerance: 3
#    min_cycle_duration:
#      seconds: 30
    initial_humidifier_mode: "humidify"
#    away_humidity: 30
  - platform: generic_hygrostat
    name: Hygrostat Zone 2
    humidifier: input_boolean.humidify_zone2
    target_sensor: sensor.zone2_humidity
    min_humidity: 0
    max_humidity: 100
    dry_mode: false
    target_humidity: 50
    dry_tolerance: 3
    wet_tolerance: 3
#    min_cycle_duration:
#      seconds: 30
    initial_humidifier_mode: "humidify"
#    away_humidity: 30
  - platform: generic_hygrostat
    name: Hygrostat Zone 3
    humidifier: input_boolean.humidify_zone3
    target_sensor: sensor.zone3_humidity
    min_humidity: 0
    max_humidity: 100
    dry_mode: false
    target_humidity: 50
    dry_tolerance: 3
    wet_tolerance: 3
#    min_cycle_duration:
#      seconds: 30
    initial_humidifier_mode: "humidify"
#    away_humidity: 30
